PR :: (#164) 댓글 페이지 서버 연동
team-nk/kim-il-jeong-android-archived pull request #165
Opened 2022-12-30 13:52 UTC by Tmdhoon2

Closes #164

2022-12-30 14:21 UTC, JunJaBoy requested changes

2022-12-30 14:21 UTC, JunJaBoy commented on app/build.gradle
> +apply plugin: 'kotlin-kapt'
이거 한 번 `'kotlin-kapt'`를 plugins {} 블록 안에 넣어보실래요? 두 개 다 사용해도 되는데 apply는 조금 더 오래된 문법이라고 합니다

2022-12-30 14:21 UTC, JunJaBoy commented on app/build.gradle
> +apply plugin: 'kotlin-kapt'
https://stackoverflow.com/questions/32352816/what-the-difference-in-applying-gradle-plugin

2022-12-30 14:21 UTC, JunJaBoy commented on app/build.gradle
> +apply plugin: 'kotlin-kapt'
그런데 apply가 조금 더 유연하다네요

2022-12-30 14:21 UTC, JunJaBoy commented on app/src/main/java/com/teamnk/kimiljung/feature/post/DetailPostActivity.kt
> +            startActivityRemovingBackStack(applicationContext, PostCommentActivity::class.java)
이 함수 사용하면 아마 메인 액티비티가 날아가지 않나요..? 아니라면 우리가 의도한 startActivity 방법이 아니게 될 것 같아요..

2022-12-30 14:21 UTC, JunJaBoy commented on app/src/main/java/com/teamnk/kimiljung/feature/postcomment/CommentListResponse.kt
> +    @SerializedName("create_time") val create_time: String,
여기 변수명은 카멜케이스로 바꿔주세요!

2022-12-30 14:21 UTC, JunJaBoy commented on app/src/main/java/com/teamnk/kimiljung/feature/postcomment/CommentViewModel.kt
> +    get() = getApplication<Application>().applicationContext
이거 아마 탭 눌러서 정렬 되지 않나요? 확인 한 번 부탁드릴게요..

2022-12-30 14:21 UTC, JunJaBoy commented on app/src/main/java/com/teamnk/kimiljung/feature/postcomment/PostCommentActivity.kt
> +        commentViewModel.commentListResponse.observe(this){
`this` 줄 바꿈 약속!

2022-12-30 14:21 UTC, JunJaBoy commented on app/src/main/java/com/teamnk/kimiljung/feature/postcomment/PostCommentActivity.kt
> +            layoutManager = LinearLayoutManager(applicationContext)
여기에 `applicationContext`를 넣으면 Activity가 메모리 릭이 발생할 겁니다. 액티비티가 스택에서 빠져야 할 때 애플리케이션의 정보를 가지고 있어서 GC가 안 될 거에요..

2022-12-30 14:21 UTC, JunJaBoy commented on app/src/main/java/com/teamnk/kimiljung/util/Adapter.kt
> +class Adapter(
이거 여기에 넣으면 안 될 것 같아요 `../feature/postcomment/` 안에 PostCommentAdapter 이런 이름으로 넣어야 할 듯 합니다

2022-12-30 14:21 UTC, JunJaBoy commented on app/src/main/java/com/teamnk/kimiljung/util/Adapter.kt
> +class Adapter(
Util은 말 그대로 여러 곳에서 다목적으로 사용할 수 있어야 하기 때문!

2022-12-30 14:21 UTC, JunJaBoy commented on app/src/main/java/com/teamnk/kimiljung/util/Adapter.kt
> +        }
이거 다 `inner class`로 만들어 보실래요? 사실 상관 없긴 한데 기본적으로 nested class로 생성되어서 혼자 인스턴스 생성.. 을 할 일 또한 없지만 inner class여야 혼자서 인스턴스 생성을 막을 수 있을 거에요

2022-12-30 14:21 UTC, JunJaBoy commented on app/src/main/java/com/teamnk/kimiljung/util/Adapter.kt
> +        }
자세한 건 요기 -> https://shinjekim.github.io/kotlin/2019/08/29/Kotlin-%EB%82%B4%EB%B6%80-%ED%81%B4%EB%9E%98%EC%8A%A4(inner-class)%EC%99%80-%EC%A4%91%EC%B2%A9-%ED%81%B4%EB%9E%98%EC%8A%A4(nested-class)/

2022-12-30 14:21 UTC, JunJaBoy commented on app/src/main/java/com/teamnk/kimiljung/util/Adapter.kt
> +                TODO()
요거 빌드 안 되어유

2022-12-30 14:21 UTC, JunJaBoy commented on app/src/main/java/com/teamnk/kimiljung/util/BindingAdapter.kt
> +        .load(profile)
여기서 `loadImage`라는 바인딩 속성은 링크만 입력하면 모든 링크를 가져올 수 있는데 실제 파라미터 이름은 `profile`이어서 헷갈리기 쉬울 것 같습니다..

2022-12-30 14:21 UTC, JunJaBoy commented on app/src/main/java/com/teamnk/kimiljung/util/BindingAdapter.kt
> +        .load(profile)
그리고 String이 nullable이면 `Glide.run`으로 하면 어떨까요? 안 되면 헉..

2022-12-30 14:21 UTC, JunJaBoy commented on app/src/main/java/com/teamnk/kimiljung/util/BindingAdapter.kt
> +        .load(profile)
안희면 String을 null로 받지 않을 수는 없나요? 궁금합니당

2022-12-30 14:46 UTC, Tmdhoon2 commented on app/src/main/java/com/teamnk/kimiljung/feature/post/DetailPostActivity.kt
> +            startActivityRemovingBackStack(applicationContext, PostCommentActivity::class.java)
아 이건 applicationContext 말고 this 로 Activity 직접 넘겨주니까 그냥 startActivity 써도 되네용 해결!

2022-12-30 14:47 UTC, Tmdhoon2 commented on app/src/main/java/com/teamnk/kimiljung/feature/post/DetailPostActivity.kt
> +            startActivityRemovingBackStack(applicationContext, PostCommentActivity::class.java)
https://devtalk.kakao.com/t/flag-activity-new-task/111688

2022-12-30 14:56 UTC, Tmdhoon2 commented on app/src/main/java/com/teamnk/kimiljung/util/Adapter.kt
> +        }
이부분은 내일 좀더 설명을.. 저는 좀 다르게 이해를 해서..

2022-12-30 15:02 UTC, Tmdhoon2 commented on app/src/main/java/com/teamnk/kimiljung/util/BindingAdapter.kt
> +        .load(profile)
아 이게 kotlin scope with 가 아니라 Glide 내부 with 군요
그리고 생각해본 결과 프로필 사진이 null로 들어오진 않을것 같네유!

2022-12-30 15:02 UTC, Tmdhoon2 commented on app/src/main/java/com/teamnk/kimiljung/util/BindingAdapter.kt
> +        .load(profile)
<img width="570" alt="스크린샷 2022-12-31 오전 12 02 19" src="https://user-images.githubusercontent.com/102812085/210084280-cf42d14e-9b19-4243-b8ee-495c42a56af9.png">

2022-12-31 00:08 UTC, JunJaBoy commented on app/src/main/java/com/teamnk/kimiljung/feature/post/DetailPostActivity.kt
> +            startActivityRemovingBackStack(applicationContext, PostCommentActivity::class.java)
아 그 뜻이 아니라 startActivityRemovingBackStack 자체가 스택에 쌓여있는 액티비티를 다 없애도록 만들어 둔 함수여서 메인 액티비티가 날아갈까 염려..

2022-12-31 01:12 UTC, JunJaBoy approved these changes

2022-12-31 01:12 UTC, JunJaBoy commented on app/src/main/java/com/teamnk/kimiljung/feature/post/PostFragment.kt
> +                    temp = 1,
`temp`가 뭔지 나중에 한 번 설명 부탁드릴게요!

2022-12-31 01:12 UTC, JunJaBoy commented on app/src/main/java/com/teamnk/kimiljung/feature/postcomment/PostCommentAdapter.kt
> +    private val temp: Int,
아 `temp`가 ViewType인가요?? viewType으로 통칭해도 될 것 같다는 생각..

2022-12-31 01:13 UTC, JunJaBoy commented on app/src/main/java/com/teamnk/kimiljung/util/BindingAdapter.kt
> +        .load(profile)
오호 알겠습니다 확장함수인 줄 알았어요..

2022-12-31 01:14 UTC, merged